# Need these for a more recent CMake on Linux
sudo: required
dist: trusty

os:
  - linux
  - osx

language: cpp

compiler:
  - clang
  - gcc

before_script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - cmake --build . --config Release -- -j12

after_script:
  - cmake --build . --target test
  
